// assert matching_return_value
if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {return true}}}}}}}}}}}};return false
// assert matching_return_value
// these tests tend to break Xcode, but we should enable them every now and then to make sure the interpreter doesn't have a stack overflow. these have passed in the past
//if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {return true}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}
return false
// assert matching_return_value
// these tests tend to break Xcode, but we should enable them every now and then to make sure the interpreter doesn't have a stack overflow. these have passed in the past
//if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {if true {return true}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}
return false
